### ISSUE TITLE
Tests show funky warnings

### ISSUE THREAD

**Issue by imagineLife** [Thinkful-Ed/redux-trello-tested#2]
Hello! 
npm test shows each test like...

' PASS  src/components/board.test.js
  ● Console

    console.error node_modules/fbjs/lib/warning.js:33
      Warning: React depends on requestAnimationFrame. Make sure that you load a polyfill in older browsers. http://fb.me/react-polyfills'

**Comment by oampo** [comment]
This is a temporary issue with `create-react-app` (see https://github.com/facebookincubator/create-react-app/issues/3199).  According to the thread it should be fixed Really Soon Now, so I'm going to let it slide until we get the fix from upstream.

**Comment by oampo** [comment]
This is a temporary issue with `create-react-app` (see https://github.com/facebookincubator/create-react-app/issues/3199).  According to the thread it should be fixed Really Soon Now, so I'm going to let it slide until we get the fix from upstream.
